# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UC_Search.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UC_Search(object):
    def setupUi(self, UC_Search):
        UC_Search.setObjectName("UC_Search")
        UC_Search.resize(1031, 800)
        UC_Search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        UC_Search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_search = QtWidgets.QFrame(UC_Search)
        self.Frame_search.setGeometry(QtCore.QRect(0, 0, 1031, 800))
        self.Frame_search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_search.setObjectName("Frame_search")
        self.Frame_Search_Results = QtWidgets.QFrame(self.Frame_search)
        self.Frame_Search_Results.setGeometry(QtCore.QRect(4, 129, 520, 660))
        self.Frame_Search_Results.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Results.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Results.setObjectName("Frame_Search_Results")
        self.label_50 = QtWidgets.QLabel(self.Frame_search)
        self.label_50.setGeometry(QtCore.QRect(480, 10, 47, 31))
        self.label_50.setObjectName("label_50")
        self.serach_cbx_type = QtWidgets.QComboBox(self.Frame_search)
        self.serach_cbx_type.setGeometry(QtCore.QRect(790, 10, 141, 39))
        self.serach_cbx_type.setObjectName("serach_cbx_type")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.serach_cbx_type.addItem("")
        self.label_52 = QtWidgets.QLabel(self.Frame_search)
        self.label_52.setGeometry(QtCore.QRect(940, 70, 71, 31))
        self.label_52.setObjectName("label_52")
        self.search_area2 = QtWidgets.QLineEdit(self.Frame_search)
        self.search_area2.setGeometry(QtCore.QRect(580, 60, 161, 35))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.search_area2.setFont(font)
        self.search_area2.setObjectName("search_area2")
        self.label_49 = QtWidgets.QLabel(self.Frame_search)
        self.label_49.setGeometry(QtCore.QRect(730, 10, 47, 31))
        self.label_49.setObjectName("label_49")
        self.search_area1 = QtWidgets.QLineEdit(self.Frame_search)
        self.search_area1.setGeometry(QtCore.QRect(770, 60, 161, 35))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.search_area1.setFont(font)
        self.search_area1.setObjectName("search_area1")
        self.label_51 = QtWidgets.QLabel(self.Frame_search)
        self.label_51.setGeometry(QtCore.QRect(180, 10, 47, 31))
        self.label_51.setObjectName("label_51")
        self.btn_search = QtWidgets.QPushButton(self.Frame_search)
        self.btn_search.setGeometry(QtCore.QRect(10, 60, 81, 40))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.btn_search.setFont(font)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setObjectName("btn_search")
        self.label_97 = QtWidgets.QLabel(self.Frame_search)
        self.label_97.setGeometry(QtCore.QRect(480, 60, 47, 31))
        self.label_97.setObjectName("label_97")
        self.label_47 = QtWidgets.QLabel(self.Frame_search)
        self.label_47.setGeometry(QtCore.QRect(940, 10, 81, 31))
        self.label_47.setObjectName("label_47")
        self.search_price1 = QtWidgets.QLineEdit(self.Frame_search)
        self.search_price1.setGeometry(QtCore.QRect(310, 60, 161, 35))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.search_price1.setFont(font)
        self.search_price1.setObjectName("search_price1")
        self.serach_cbx_block = QtWidgets.QComboBox(self.Frame_search)
        self.serach_cbx_block.setGeometry(QtCore.QRect(10, 10, 141, 39))
        self.serach_cbx_block.setObjectName("serach_cbx_block")
        self.serach_cbx_city = QtWidgets.QComboBox(self.Frame_search)
        self.serach_cbx_city.setGeometry(QtCore.QRect(540, 10, 181, 39))
        self.serach_cbx_city.setObjectName("serach_cbx_city")
        self.search_price2 = QtWidgets.QLineEdit(self.Frame_search)
        self.search_price2.setGeometry(QtCore.QRect(120, 60, 161, 35))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.search_price2.setFont(font)
        self.search_price2.setObjectName("search_price2")
        self.serach_cbx_street = QtWidgets.QComboBox(self.Frame_search)
        self.serach_cbx_street.setGeometry(QtCore.QRect(250, 10, 221, 39))
        self.serach_cbx_street.setObjectName("serach_cbx_street")
        self.line = QtWidgets.QFrame(self.Frame_search)
        self.line.setGeometry(QtCore.QRect(130, 110, 800, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Frame_Search_Navigator = QtWidgets.QFrame(self.Frame_search)
        self.Frame_Search_Navigator.setGeometry(QtCore.QRect(530, 130, 490, 660))
        self.Frame_Search_Navigator.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Navigator.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Navigator.setObjectName("Frame_Search_Navigator")
        self.Frame_Search_Emarah = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_Emarah.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_Emarah.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Emarah.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Emarah.setObjectName("Frame_Search_Emarah")
        self.checkBox_21 = QtWidgets.QCheckBox(self.Frame_Search_Emarah)
        self.checkBox_21.setGeometry(QtCore.QRect(140, 180, 81, 30))
        self.checkBox_21.setObjectName("checkBox_21")
        self.checkBox_20 = QtWidgets.QCheckBox(self.Frame_Search_Emarah)
        self.checkBox_20.setGeometry(QtCore.QRect(260, 180, 81, 30))
        self.checkBox_20.setObjectName("checkBox_20")
        self.label_827 = QtWidgets.QLabel(self.Frame_Search_Emarah)
        self.label_827.setGeometry(QtCore.QRect(360, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_827.setFont(font)
        self.label_827.setObjectName("label_827")
        self.checkBox_12 = QtWidgets.QCheckBox(self.Frame_Search_Emarah)
        self.checkBox_12.setGeometry(QtCore.QRect(20, 180, 81, 30))
        self.checkBox_12.setObjectName("checkBox_12")
        self.lineEdit_634 = QtWidgets.QLineEdit(self.Frame_Search_Emarah)
        self.lineEdit_634.setGeometry(QtCore.QRect(10, 100, 330, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_634.setFont(font)
        self.lineEdit_634.setObjectName("lineEdit_634")
        self.label_99 = QtWidgets.QLabel(self.Frame_Search_Emarah)
        self.label_99.setGeometry(QtCore.QRect(370, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.comboBox_26 = QtWidgets.QComboBox(self.Frame_Search_Emarah)
        self.comboBox_26.setGeometry(QtCore.QRect(10, 30, 330, 49))
        self.comboBox_26.setObjectName("comboBox_26")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.comboBox_26.addItem("")
        self.label_101 = QtWidgets.QLabel(self.Frame_Search_Emarah)
        self.label_101.setGeometry(QtCore.QRect(360, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.Frame_Search_Villa = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_Villa.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_Villa.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Villa.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Villa.setObjectName("Frame_Search_Villa")
        self.label_829 = QtWidgets.QLabel(self.Frame_Search_Villa)
        self.label_829.setGeometry(QtCore.QRect(350, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_829.setFont(font)
        self.label_829.setObjectName("label_829")
        self.label_831 = QtWidgets.QLabel(self.Frame_Search_Villa)
        self.label_831.setGeometry(QtCore.QRect(350, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_831.setFont(font)
        self.label_831.setObjectName("label_831")
        self.comboBox_179 = QtWidgets.QComboBox(self.Frame_Search_Villa)
        self.comboBox_179.setGeometry(QtCore.QRect(10, 90, 330, 49))
        self.comboBox_179.setObjectName("comboBox_179")
        self.comboBox_179.addItem("")
        self.comboBox_179.addItem("")
        self.comboBox_179.addItem("")
        self.label_830 = QtWidgets.QLabel(self.Frame_Search_Villa)
        self.label_830.setGeometry(QtCore.QRect(360, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_830.setFont(font)
        self.label_830.setObjectName("label_830")
        self.checkBox_166 = QtWidgets.QCheckBox(self.Frame_Search_Villa)
        self.checkBox_166.setGeometry(QtCore.QRect(130, 250, 81, 30))
        self.checkBox_166.setObjectName("checkBox_166")
        self.lineEdit_636 = QtWidgets.QLineEdit(self.Frame_Search_Villa)
        self.lineEdit_636.setGeometry(QtCore.QRect(10, 20, 330, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_636.setFont(font)
        self.lineEdit_636.setObjectName("lineEdit_636")
        self.checkBox_168 = QtWidgets.QCheckBox(self.Frame_Search_Villa)
        self.checkBox_168.setGeometry(QtCore.QRect(10, 250, 81, 30))
        self.checkBox_168.setObjectName("checkBox_168")
        self.comboBox_180 = QtWidgets.QComboBox(self.Frame_Search_Villa)
        self.comboBox_180.setGeometry(QtCore.QRect(10, 170, 330, 49))
        self.comboBox_180.setObjectName("comboBox_180")
        self.comboBox_180.addItem("")
        self.comboBox_180.addItem("")
        self.comboBox_180.addItem("")
        self.comboBox_180.addItem("")
        self.label_832 = QtWidgets.QLabel(self.Frame_Search_Villa)
        self.label_832.setGeometry(QtCore.QRect(370, 180, 101, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_832.setFont(font)
        self.label_832.setObjectName("label_832")
        self.checkBox_167 = QtWidgets.QCheckBox(self.Frame_Search_Villa)
        self.checkBox_167.setGeometry(QtCore.QRect(250, 250, 81, 30))
        self.checkBox_167.setObjectName("checkBox_167")
        self.Frame_Search_NormalFlat = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_NormalFlat.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_NormalFlat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_NormalFlat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_NormalFlat.setObjectName("Frame_Search_NormalFlat")
        self.label_835 = QtWidgets.QLabel(self.Frame_Search_NormalFlat)
        self.label_835.setGeometry(QtCore.QRect(350, 210, 100, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_835.setFont(font)
        self.label_835.setObjectName("label_835")
        self.label_838 = QtWidgets.QLabel(self.Frame_Search_NormalFlat)
        self.label_838.setGeometry(QtCore.QRect(350, 30, 100, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_838.setFont(font)
        self.label_838.setObjectName("label_838")
        self.lineEdit_642 = QtWidgets.QLineEdit(self.Frame_Search_NormalFlat)
        self.lineEdit_642.setGeometry(QtCore.QRect(20, 20, 310, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_642.setFont(font)
        self.lineEdit_642.setObjectName("lineEdit_642")
        self.label_834 = QtWidgets.QLabel(self.Frame_Search_NormalFlat)
        self.label_834.setGeometry(QtCore.QRect(350, 80, 100, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_834.setFont(font)
        self.label_834.setObjectName("label_834")
        self.label_840 = QtWidgets.QLabel(self.Frame_Search_NormalFlat)
        self.label_840.setGeometry(QtCore.QRect(350, 330, 100, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_840.setFont(font)
        self.label_840.setObjectName("label_840")
        self.checkBox_200 = QtWidgets.QCheckBox(self.Frame_Search_NormalFlat)
        self.checkBox_200.setGeometry(QtCore.QRect(260, 320, 61, 30))
        self.checkBox_200.setObjectName("checkBox_200")
        self.label_836 = QtWidgets.QLabel(self.Frame_Search_NormalFlat)
        self.label_836.setGeometry(QtCore.QRect(350, 150, 100, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_836.setFont(font)
        self.label_836.setObjectName("label_836")
        self.label_839 = QtWidgets.QLabel(self.Frame_Search_NormalFlat)
        self.label_839.setGeometry(QtCore.QRect(350, 270, 100, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_839.setFont(font)
        self.label_839.setObjectName("label_839")
        self.lineEdit_639 = QtWidgets.QLineEdit(self.Frame_Search_NormalFlat)
        self.lineEdit_639.setGeometry(QtCore.QRect(20, 260, 310, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_639.setFont(font)
        self.lineEdit_639.setObjectName("lineEdit_639")
        self.checkBox_199 = QtWidgets.QCheckBox(self.Frame_Search_NormalFlat)
        self.checkBox_199.setGeometry(QtCore.QRect(165, 320, 51, 30))
        self.checkBox_199.setObjectName("checkBox_199")
        self.lineEdit_638 = QtWidgets.QLineEdit(self.Frame_Search_NormalFlat)
        self.lineEdit_638.setGeometry(QtCore.QRect(20, 140, 310, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_638.setFont(font)
        self.lineEdit_638.setObjectName("lineEdit_638")
        self.comboBox_181 = QtWidgets.QComboBox(self.Frame_Search_NormalFlat)
        self.comboBox_181.setGeometry(QtCore.QRect(20, 80, 310, 49))
        self.comboBox_181.setObjectName("comboBox_181")
        self.comboBox_181.addItem("")
        self.comboBox_181.addItem("")
        self.comboBox_181.addItem("")
        self.comboBox_181.addItem("")
        self.lineEdit_640 = QtWidgets.QLineEdit(self.Frame_Search_NormalFlat)
        self.lineEdit_640.setGeometry(QtCore.QRect(20, 200, 310, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_640.setFont(font)
        self.lineEdit_640.setObjectName("lineEdit_640")
        self.checkBox_201 = QtWidgets.QCheckBox(self.Frame_Search_NormalFlat)
        self.checkBox_201.setGeometry(QtCore.QRect(60, 320, 51, 30))
        self.checkBox_201.setObjectName("checkBox_201")
        self.Frame_Search_DoublexFlat = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_DoublexFlat.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_DoublexFlat.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_DoublexFlat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_DoublexFlat.setObjectName("Frame_Search_DoublexFlat")
        self.checkBox_176 = QtWidgets.QCheckBox(self.Frame_Search_DoublexFlat)
        self.checkBox_176.setGeometry(QtCore.QRect(30, 340, 81, 30))
        self.checkBox_176.setObjectName("checkBox_176")
        self.checkBox_177 = QtWidgets.QCheckBox(self.Frame_Search_DoublexFlat)
        self.checkBox_177.setGeometry(QtCore.QRect(250, 340, 81, 30))
        self.checkBox_177.setObjectName("checkBox_177")
        self.checkBox_175 = QtWidgets.QCheckBox(self.Frame_Search_DoublexFlat)
        self.checkBox_175.setGeometry(QtCore.QRect(130, 340, 81, 30))
        self.checkBox_175.setObjectName("checkBox_175")
        self.comboBox_182 = QtWidgets.QComboBox(self.Frame_Search_DoublexFlat)
        self.comboBox_182.setGeometry(QtCore.QRect(10, 270, 330, 49))
        self.comboBox_182.setObjectName("comboBox_182")
        self.comboBox_182.addItem("")
        self.comboBox_182.addItem("")
        self.comboBox_182.addItem("")
        self.comboBox_182.addItem("")
        self.label_846 = QtWidgets.QLabel(self.Frame_Search_DoublexFlat)
        self.label_846.setGeometry(QtCore.QRect(360, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_846.setFont(font)
        self.label_846.setObjectName("label_846")
        self.checkBox_178 = QtWidgets.QCheckBox(self.Frame_Search_DoublexFlat)
        self.checkBox_178.setGeometry(QtCore.QRect(280, 440, 61, 30))
        self.checkBox_178.setObjectName("checkBox_178")
        self.checkBox_172 = QtWidgets.QCheckBox(self.Frame_Search_DoublexFlat)
        self.checkBox_172.setGeometry(QtCore.QRect(250, 390, 91, 30))
        self.checkBox_172.setObjectName("checkBox_172")
        self.label_844 = QtWidgets.QLabel(self.Frame_Search_DoublexFlat)
        self.label_844.setGeometry(QtCore.QRect(360, 270, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_844.setFont(font)
        self.label_844.setObjectName("label_844")
        self.comboBox_183 = QtWidgets.QComboBox(self.Frame_Search_DoublexFlat)
        self.comboBox_183.setGeometry(QtCore.QRect(10, 210, 330, 49))
        self.comboBox_183.setObjectName("comboBox_183")
        self.comboBox_183.addItem("")
        self.comboBox_183.addItem("")
        self.comboBox_183.addItem("")
        self.comboBox_183.addItem("")
        self.label_843 = QtWidgets.QLabel(self.Frame_Search_DoublexFlat)
        self.label_843.setGeometry(QtCore.QRect(360, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_843.setFont(font)
        self.label_843.setObjectName("label_843")
        self.lineEdit_646 = QtWidgets.QLineEdit(self.Frame_Search_DoublexFlat)
        self.lineEdit_646.setGeometry(QtCore.QRect(10, 10, 330, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_646.setFont(font)
        self.lineEdit_646.setObjectName("lineEdit_646")
        self.label_842 = QtWidgets.QLabel(self.Frame_Search_DoublexFlat)
        self.label_842.setGeometry(QtCore.QRect(360, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_842.setFont(font)
        self.label_842.setObjectName("label_842")
        self.lineEdit_643 = QtWidgets.QLineEdit(self.Frame_Search_DoublexFlat)
        self.lineEdit_643.setGeometry(QtCore.QRect(10, 90, 330, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_643.setFont(font)
        self.lineEdit_643.setObjectName("lineEdit_643")
        self.label_841 = QtWidgets.QLabel(self.Frame_Search_DoublexFlat)
        self.label_841.setGeometry(QtCore.QRect(360, 380, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_841.setFont(font)
        self.label_841.setObjectName("label_841")
        self.lineEdit_644 = QtWidgets.QLineEdit(self.Frame_Search_DoublexFlat)
        self.lineEdit_644.setGeometry(QtCore.QRect(10, 150, 330, 41))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.lineEdit_644.setFont(font)
        self.lineEdit_644.setObjectName("lineEdit_644")
        self.checkBox_173 = QtWidgets.QCheckBox(self.Frame_Search_DoublexFlat)
        self.checkBox_173.setGeometry(QtCore.QRect(40, 390, 81, 30))
        self.checkBox_173.setObjectName("checkBox_173")
        self.label_847 = QtWidgets.QLabel(self.Frame_Search_DoublexFlat)
        self.label_847.setGeometry(QtCore.QRect(360, 330, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_847.setFont(font)
        self.label_847.setObjectName("label_847")
        self.label_845 = QtWidgets.QLabel(self.Frame_Search_DoublexFlat)
        self.label_845.setGeometry(QtCore.QRect(360, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_845.setFont(font)
        self.label_845.setObjectName("label_845")
        self.checkBox_174 = QtWidgets.QCheckBox(self.Frame_Search_DoublexFlat)
        self.checkBox_174.setGeometry(QtCore.QRect(130, 390, 91, 30))
        self.checkBox_174.setObjectName("checkBox_174")
        self.Frame_Search_Factories = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_Factories.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_Factories.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Factories.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Factories.setObjectName("Frame_Search_Factories")
        self.comboBox_185 = QtWidgets.QComboBox(self.Frame_Search_Factories)
        self.comboBox_185.setGeometry(QtCore.QRect(10, 20, 330, 49))
        self.comboBox_185.setObjectName("comboBox_185")
        self.comboBox_185.addItem("")
        self.comboBox_185.addItem("")
        self.label_857 = QtWidgets.QLabel(self.Frame_Search_Factories)
        self.label_857.setGeometry(QtCore.QRect(360, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_857.setFont(font)
        self.label_857.setObjectName("label_857")
        self.Frame_Search_Lands = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_Lands.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_Lands.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Lands.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Lands.setObjectName("Frame_Search_Lands")
        self.label_859 = QtWidgets.QLabel(self.Frame_Search_Lands)
        self.label_859.setGeometry(QtCore.QRect(360, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_859.setFont(font)
        self.label_859.setObjectName("label_859")
        self.comboBox_186 = QtWidgets.QComboBox(self.Frame_Search_Lands)
        self.comboBox_186.setGeometry(QtCore.QRect(10, 110, 330, 49))
        self.comboBox_186.setObjectName("comboBox_186")
        self.comboBox_186.addItem("")
        self.comboBox_186.addItem("")
        self.comboBox_186.addItem("")
        self.comboBox_186.addItem("")
        self.comboBox_186.addItem("")
        self.comboBox_186.addItem("")
        self.comboBox_187 = QtWidgets.QComboBox(self.Frame_Search_Lands)
        self.comboBox_187.setGeometry(QtCore.QRect(10, 10, 330, 49))
        self.comboBox_187.setObjectName("comboBox_187")
        self.comboBox_187.addItem("")
        self.comboBox_187.addItem("")
        self.label_861 = QtWidgets.QLabel(self.Frame_Search_Lands)
        self.label_861.setGeometry(QtCore.QRect(360, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_861.setFont(font)
        self.label_861.setObjectName("label_861")
        self.Frame_search_ServicesBuilding = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_search_ServicesBuilding.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_search_ServicesBuilding.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_search_ServicesBuilding.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_search_ServicesBuilding.setObjectName("Frame_search_ServicesBuilding")
        self.lineEdit_658 = QtWidgets.QLineEdit(self.Frame_search_ServicesBuilding)
        self.lineEdit_658.setGeometry(QtCore.QRect(20, 80, 310, 41))
        self.lineEdit_658.setObjectName("lineEdit_658")
        self.checkBox_180 = QtWidgets.QCheckBox(self.Frame_search_ServicesBuilding)
        self.checkBox_180.setGeometry(QtCore.QRect(250, 200, 61, 31))
        self.checkBox_180.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_180.setObjectName("checkBox_180")
        self.label_862 = QtWidgets.QLabel(self.Frame_search_ServicesBuilding)
        self.label_862.setGeometry(QtCore.QRect(340, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_862.setFont(font)
        self.label_862.setObjectName("label_862")
        self.label_863 = QtWidgets.QLabel(self.Frame_search_ServicesBuilding)
        self.label_863.setGeometry(QtCore.QRect(340, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_863.setFont(font)
        self.label_863.setObjectName("label_863")
        self.label_848 = QtWidgets.QLabel(self.Frame_search_ServicesBuilding)
        self.label_848.setGeometry(QtCore.QRect(340, 200, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_848.setFont(font)
        self.label_848.setObjectName("label_848")
        self.checkBox_179 = QtWidgets.QCheckBox(self.Frame_search_ServicesBuilding)
        self.checkBox_179.setGeometry(QtCore.QRect(155, 200, 61, 31))
        self.checkBox_179.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_179.setObjectName("checkBox_179")
        self.lineEdit_657 = QtWidgets.QLineEdit(self.Frame_search_ServicesBuilding)
        self.lineEdit_657.setGeometry(QtCore.QRect(20, 20, 310, 41))
        self.lineEdit_657.setText("")
        self.lineEdit_657.setObjectName("lineEdit_657")
        self.lineEdit_656 = QtWidgets.QLineEdit(self.Frame_search_ServicesBuilding)
        self.lineEdit_656.setGeometry(QtCore.QRect(20, 140, 310, 41))
        self.lineEdit_656.setText("")
        self.lineEdit_656.setObjectName("lineEdit_656")
        self.label_864 = QtWidgets.QLabel(self.Frame_search_ServicesBuilding)
        self.label_864.setGeometry(QtCore.QRect(340, 150, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_864.setFont(font)
        self.label_864.setObjectName("label_864")
        self.checkBox_181 = QtWidgets.QCheckBox(self.Frame_search_ServicesBuilding)
        self.checkBox_181.setGeometry(QtCore.QRect(60, 200, 61, 31))
        self.checkBox_181.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_181.setObjectName("checkBox_181")
        self.Frame_Search_ServicesUnit = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_ServicesUnit.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_ServicesUnit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_ServicesUnit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_ServicesUnit.setObjectName("Frame_Search_ServicesUnit")
        self.label_867 = QtWidgets.QLabel(self.Frame_Search_ServicesUnit)
        self.label_867.setGeometry(QtCore.QRect(350, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_867.setFont(font)
        self.label_867.setObjectName("label_867")
        self.lineEdit_660 = QtWidgets.QLineEdit(self.Frame_Search_ServicesUnit)
        self.lineEdit_660.setGeometry(QtCore.QRect(20, 90, 310, 41))
        self.lineEdit_660.setObjectName("lineEdit_660")
        self.checkBox_182 = QtWidgets.QCheckBox(self.Frame_Search_ServicesUnit)
        self.checkBox_182.setGeometry(QtCore.QRect(170, 160, 61, 31))
        self.checkBox_182.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_182.setObjectName("checkBox_182")
        self.lineEdit_662 = QtWidgets.QLineEdit(self.Frame_Search_ServicesUnit)
        self.lineEdit_662.setGeometry(QtCore.QRect(20, 20, 310, 41))
        self.lineEdit_662.setObjectName("lineEdit_662")
        self.checkBox_183 = QtWidgets.QCheckBox(self.Frame_Search_ServicesUnit)
        self.checkBox_183.setGeometry(QtCore.QRect(265, 160, 61, 31))
        self.checkBox_183.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_183.setObjectName("checkBox_183")
        self.label_866 = QtWidgets.QLabel(self.Frame_Search_ServicesUnit)
        self.label_866.setGeometry(QtCore.QRect(350, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_866.setFont(font)
        self.label_866.setObjectName("label_866")
        self.label_868 = QtWidgets.QLabel(self.Frame_Search_ServicesUnit)
        self.label_868.setGeometry(QtCore.QRect(350, 160, 121, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_868.setFont(font)
        self.label_868.setObjectName("label_868")
        self.Frame_Search_Eductional = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_Eductional.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_Eductional.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Eductional.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Eductional.setObjectName("Frame_Search_Eductional")
        self.label_870 = QtWidgets.QLabel(self.Frame_Search_Eductional)
        self.label_870.setGeometry(QtCore.QRect(390, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily("simplified arabic")
        self.label_870.setFont(font)
        self.label_870.setObjectName("label_870")
        self.comboBox_188 = QtWidgets.QComboBox(self.Frame_Search_Eductional)
        self.comboBox_188.setGeometry(QtCore.QRect(30, 20, 330, 49))
        self.comboBox_188.setObjectName("comboBox_188")
        self.comboBox_188.addItem("")
        self.comboBox_188.addItem("")
        self.Frame_Search_Hospital = QtWidgets.QFrame(self.Frame_Search_Navigator)
        self.Frame_Search_Hospital.setGeometry(QtCore.QRect(0, 0, 490, 660))
        self.Frame_Search_Hospital.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Search_Hospital.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Search_Hospital.setObjectName("Frame_Search_Hospital")

        self.retranslateUi(UC_Search)
        self.serach_cbx_type.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(UC_Search)

    def retranslateUi(self, UC_Search):
        _translate = QtCore.QCoreApplication.translate
        UC_Search.setWindowTitle(_translate("UC_Search", "Frame"))
        self.label_50.setText(_translate("UC_Search", "الحي"))
        self.serach_cbx_type.setItemText(0, _translate("UC_Search", "عمارات"))
        self.serach_cbx_type.setItemText(1, _translate("UC_Search", "فيلا"))
        self.serach_cbx_type.setItemText(2, _translate("UC_Search", "شقق عادية "))
        self.serach_cbx_type.setItemText(3, _translate("UC_Search", "دوبلكس"))
        self.serach_cbx_type.setItemText(4, _translate("UC_Search", "مصانع"))
        self.serach_cbx_type.setItemText(5, _translate("UC_Search", "اراضي"))
        self.serach_cbx_type.setItemText(6, _translate("UC_Search", "مبني خدمي"))
        self.serach_cbx_type.setItemText(7, _translate("UC_Search", "وحدة خدمي"))
        self.serach_cbx_type.setItemText(8, _translate("UC_Search", "تعليمي"))
        self.serach_cbx_type.setItemText(9, _translate("UC_Search", "صحي"))
        self.label_52.setText(_translate("UC_Search", "المساحة"))
        self.search_area2.setPlaceholderText(_translate("UC_Search", "  القيمه النهائيه"))
        self.label_49.setText(_translate("UC_Search", "المدينة"))
        self.search_area1.setPlaceholderText(_translate("UC_Search", "  القيمه الإبتدائيه"))
        self.label_51.setText(_translate("UC_Search", "البلوك"))
        self.btn_search.setText(_translate("UC_Search", "بحث"))
        self.label_97.setText(_translate("UC_Search", "السعر"))
        self.label_47.setText(_translate("UC_Search", " نوع العقار"))
        self.search_price1.setPlaceholderText(_translate("UC_Search", "  القيمه الإبتدائيه"))
        self.search_price2.setPlaceholderText(_translate("UC_Search", "  القيمه النهائيه"))
        self.checkBox_21.setText(_translate("UC_Search", "مياه"))
        self.checkBox_20.setText(_translate("UC_Search", "كهربا"))
        self.label_827.setText(_translate("UC_Search", " نوع التشطيب"))
        self.checkBox_12.setText(_translate("UC_Search", "غاز"))
        self.label_99.setText(_translate("UC_Search", "المرافق"))
        self.comboBox_26.setItemText(0, _translate("UC_Search", "منظمه"))
        self.comboBox_26.setItemText(1, _translate("UC_Search", "تحت التشطيب"))
        self.comboBox_26.setItemText(2, _translate("UC_Search", "طوب أحمر"))
        self.comboBox_26.setItemText(3, _translate("UC_Search", "هيكل خرصانى"))
        self.label_101.setText(_translate("UC_Search", "عدد الطوابق"))
        self.label_829.setText(_translate("UC_Search", " نوع الفيلا"))
        self.label_831.setText(_translate("UC_Search", " عدد الطوابق"))
        self.comboBox_179.setItemText(0, _translate("UC_Search", "خاصه"))
        self.comboBox_179.setItemText(1, _translate("UC_Search", "عاديه"))
        self.comboBox_179.setItemText(2, _translate("UC_Search", "حمام سباحه"))
        self.label_830.setText(_translate("UC_Search", "المرافق"))
        self.checkBox_166.setText(_translate("UC_Search", "مياه"))
        self.checkBox_168.setText(_translate("UC_Search", "غاز"))
        self.comboBox_180.setItemText(0, _translate("UC_Search", "منظمه"))
        self.comboBox_180.setItemText(1, _translate("UC_Search", "تحت التشطيب"))
        self.comboBox_180.setItemText(2, _translate("UC_Search", "طوب أحمر"))
        self.comboBox_180.setItemText(3, _translate("UC_Search", "هيكل خرصانى"))
        self.label_832.setText(_translate("UC_Search", " نوع التشطيب"))
        self.checkBox_167.setText(_translate("UC_Search", "كهربا"))
        self.label_835.setText(_translate("UC_Search", "عدد الغرف"))
        self.label_838.setText(_translate("UC_Search", "القطعه"))
        self.label_834.setText(_translate("UC_Search", "نوع التشطيب"))
        self.label_840.setText(_translate("UC_Search", "المرافق"))
        self.checkBox_200.setText(_translate("UC_Search", "كهربا"))
        self.label_836.setText(_translate("UC_Search", "الدور"))
        self.label_839.setText(_translate("UC_Search", "عدد الحمامات"))
        self.checkBox_199.setText(_translate("UC_Search", "مياه"))
        self.comboBox_181.setItemText(0, _translate("UC_Search", "منظمه"))
        self.comboBox_181.setItemText(1, _translate("UC_Search", "تحت التشطيب"))
        self.comboBox_181.setItemText(2, _translate("UC_Search", "طوب أحمر"))
        self.comboBox_181.setItemText(3, _translate("UC_Search", "هيكل خرصانى"))
        self.checkBox_201.setText(_translate("UC_Search", "غاز"))
        self.checkBox_176.setText(_translate("UC_Search", "غاز"))
        self.checkBox_177.setText(_translate("UC_Search", "كهربا"))
        self.checkBox_175.setText(_translate("UC_Search", "مياه"))
        self.comboBox_182.setItemText(0, _translate("UC_Search", "منظمه"))
        self.comboBox_182.setItemText(1, _translate("UC_Search", "تحت التشطيب"))
        self.comboBox_182.setItemText(2, _translate("UC_Search", "طوب أحمر"))
        self.comboBox_182.setItemText(3, _translate("UC_Search", "هيكل خرصانى"))
        self.label_846.setText(_translate("UC_Search", "القطعه"))
        self.checkBox_178.setText(_translate("UC_Search", "جاردن"))
        self.checkBox_172.setText(_translate("UC_Search", "حمام سباحة"))
        self.label_844.setText(_translate("UC_Search", "نوع التشطيب"))
        self.comboBox_183.setItemText(0, _translate("UC_Search", "بيزمنت"))
        self.comboBox_183.setItemText(1, _translate("UC_Search", "ارضي "))
        self.comboBox_183.setItemText(2, _translate("UC_Search", "متكرر"))
        self.comboBox_183.setItemText(3, _translate("UC_Search", "روف"))
        self.label_843.setText(_translate("UC_Search", "نوع الدوبلكس"))
        self.label_842.setText(_translate("UC_Search", "عدد الغرف"))
        self.label_841.setText(_translate("UC_Search", "مميزات"))
        self.checkBox_173.setText(_translate("UC_Search", "سلم داخلي"))
        self.label_847.setText(_translate("UC_Search", "المرافق"))
        self.label_845.setText(_translate("UC_Search", "عدد الحمامات"))
        self.checkBox_174.setText(_translate("UC_Search", "مدخل خاص"))
        self.comboBox_185.setItemText(0, _translate("UC_Search", "جمالون"))
        self.comboBox_185.setItemText(1, _translate("UC_Search", "مبني متعدد الادوار"))
        self.label_857.setText(_translate("UC_Search", " نوع المصنع"))
        self.label_859.setText(_translate("UC_Search", " نوع الارض"))
        self.comboBox_186.setItemText(0, _translate("UC_Search", "اكثر تميزا"))
        self.comboBox_186.setItemText(1, _translate("UC_Search", "اجتماعي"))
        self.comboBox_186.setItemText(2, _translate("UC_Search", "صناعي"))
        self.comboBox_186.setItemText(3, _translate("UC_Search", "بيت وطن"))
        self.comboBox_186.setItemText(4, _translate("UC_Search", "سكني"))
        self.comboBox_186.setItemText(5, _translate("UC_Search", "خدمي"))
        self.comboBox_187.setItemText(0, _translate("UC_Search", "محجوز"))
        self.comboBox_187.setItemText(1, _translate("UC_Search", "فضاء"))
        self.label_861.setText(_translate("UC_Search", " حالة الارض"))
        self.checkBox_180.setText(_translate("UC_Search", "إدارى"))
        self.label_862.setText(_translate("UC_Search", "عدد الادوار"))
        self.label_863.setText(_translate("UC_Search", "اسم المبنى"))
        self.label_848.setText(_translate("UC_Search", "المرافق"))
        self.checkBox_179.setText(_translate("UC_Search", "تجارى"))
        self.label_864.setText(_translate("UC_Search", "عدد الوحدات"))
        self.checkBox_181.setText(_translate("UC_Search", "سكنى"))
        self.label_867.setText(_translate("UC_Search", "اسم الوحدة"))
        self.checkBox_182.setText(_translate("UC_Search", "تجارى"))
        self.checkBox_183.setText(_translate("UC_Search", "إدارى"))
        self.label_866.setText(_translate("UC_Search", "القطعه"))
        self.label_868.setText(_translate("UC_Search", "نوع الوحده"))
        self.label_870.setText(_translate("UC_Search", " نوع المبني "))
        self.comboBox_188.setItemText(0, _translate("UC_Search", "مدارس"))
        self.comboBox_188.setItemText(1, _translate("UC_Search", "حضانات"))


